import constants
import drivers

LEADERBOARD = {
    constants.HAMILTON: drivers.hamilton,
    constants.VERSTAPPEN: drivers.verstappen,
    constants.BOTTAS: drivers.bottas,
    constants.PEREZ: drivers.perez,
    constants.LECLERC: drivers.leclerc,
    constants.GASLY: drivers.gasly,
    constants.RICCIARDO: drivers.ricciardo,
    constants.NORRIS: drivers.norris,
    constants.SAINZ: drivers.sainz,
    constants.TSUNODA: drivers.tsunoda,
    constants.STROLL: drivers.stroll,
    constants.ALONSO: drivers.alonso,
    constants.VETTEL: drivers.vettel,
    constants.OCON: drivers.ocon,
    constants.RUSSELL: drivers.russell,
    constants.LATIFI: drivers.latifi,
    constants.RAIKKONEN: drivers.raikkonen,
    constants.GIOVINAZZI: drivers.giovinazzi,
    constants.MAZEPIN: drivers.mazepin,
    constants.SCHUMACHER: drivers.schumacher,
}


# LEADERBOARD = {
#     constants.HAMILTON: drivers.hamilton,
#     constants.VERSTAPPEN: drivers.verstappen,
#     constants.BOTTAS: drivers.bottas,
#     constants.PEREZ: drivers.perez,
#     constants.RICCIARDO: drivers.ricciardo,
#     constants.NORRIS: drivers.norris,
#     constants.GASLY: drivers.gasly,
#     constants.VETTEL: drivers.vettel,
#     constants.LECLERC: drivers.leclerc,
#     constants.STROLL: drivers.stroll,
#     constants.TSUNODA: drivers.tsunoda,
#     constants.ALONSO: drivers.alonso,
#     constants.OCON: drivers.ocon,
#     constants.SAINZ: drivers.sainz,
#     constants.GIOVINAZZI: drivers.giovinazzi,
#     constants.RAIKKONEN: drivers.raikkonen,
#     constants.RUSSELL: drivers.russell,
#     constants.LATIFI: drivers.latifi,
#     constants.MAZEPIN: drivers.mazepin,
#     constants.SCHUMACHER: drivers.schumacher,
# }


# LEADERBOARD = {
#     constants.VERSTAPPEN: drivers.verstappen,
#     constants.HAMILTON: drivers.hamilton,
#     constants.BOTTAS: drivers.bottas,
#     constants.PEREZ: drivers.perez,
#     constants.LECLERC: drivers.leclerc,
#     constants.RICCIARDO: drivers.ricciardo,
#     constants.NORRIS: drivers.norris,
#     constants.GASLY: drivers.gasly,
#     constants.SAINZ: drivers.sainz,
#     constants.TSUNODA: drivers.tsunoda,
#     constants.ALONSO: drivers.alonso,
#     constants.STROLL: drivers.stroll,
#     constants.VETTEL: drivers.vettel,
#     constants.OCON: drivers.ocon,
#     constants.RAIKKONEN: drivers.raikkonen,
#     constants.GIOVINAZZI: drivers.giovinazzi,
#     constants.RUSSELL: drivers.russell,
#     constants.LATIFI: drivers.latifi,
#     constants.SCHUMACHER: drivers.schumacher,
#     constants.MAZEPIN: drivers.mazepin,
# }
